### ISSUE TITLE
Use without Redis

### ISSUE THREAD

**Issue by withjam** [share/livedb#52]
You have a done a great job of abstracting out the db api, and I am currently working on a custom implementation.  However, I would also like to have the option of eliminating redis as the driver in favor of a different DB.  I did not see any similar documentation on creating a custom driver.  Is it currently possible to use/build a driver that uses something other than Redis?

**Comment by zag2art** [comment]
> However, I would also like to have the option of eliminating redis as the driver in favor of a different DB.

For now it's possible to use livedb without redis but it works only with one server case. I think there is no specific docs but you can take a look at https://github.com/share/livedb/blob/master/lib/redisdriver.js (it is used when livedb uses redis) and  https://github.com/share/livedb/blob/master/lib/inprocessdriver.js (it is used when livedb works without redis [one instance mode]). You can try to find the difference. Mainly redis driver uses pub/sub to inform other server-instances about changes.

As far as I know Joseph wanted to move `redisdriver` outside of livedb but at the moment it is still there.

I hope it's helpfull.

**Comment by josephg** [comment]
Yep exactly. Redis is used for multi-server sync and as a simple way to do atomic operations. If you have two livedb frontends, each with a client connected to the same document, you need to handle these cases:

- One user sends an operation to the document. The user connected to the other server needs to be notified. (Pubsub)
- Users on two servers both try and submit an operation at the same time. Those operations should both succeed, but one of them will become operation N and the other operation N+1. So you need a way to atomically submit to the document.

If you just have one server, both of these problems go away, hence the in-process driver. I abstracted out the 'driver' API because I had plans to make a driver using foundationdb - which would remove the single source of failure of redis. But unfortunately fdb has been bought by apple and is no longer avaliable.

That said, you're welcome to take a look at that driver code and write your own implementation. I won't promise that the API will never change, but I don't have any changes planned anytime soon.

**Comment by withjam** [comment]
Great, thank you!  I am planning on building a driver for use on MarkLogic so that I can eliminate the need for any other db installation.  I will take a look at your example and see if I can get something working.

**Comment by josephg** [comment]
:+1:
